/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthDeviceRouteImport } from './routes/auth/device'
import { Route as Char126dashLoginRouteRouteImport } from './routes/~dash.$login/route'
import { Route as Char126dashLoginIndexRouteImport } from './routes/~dash.$login/index'
import { Route as Char126dashLoginRequestsRouteImport } from './routes/~dash.$login/requests'
import { Route as CreditsAddIdRouteImport } from './routes/credits.add.$id'
import { Route as Char126dashLoginSettingsTokensRouteImport } from './routes/~dash.$login/settings.tokens'
import { Route as Char126dashLoginSettingsMembersRouteImport } from './routes/~dash.$login/settings.members'
import { Route as Char126dashLoginSettingsGeneralRouteImport } from './routes/~dash.$login/settings.general'
import { Route as Char126dashLoginSettingsBillingRouteImport } from './routes/~dash.$login/settings.billing'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126dashLoginRouteRoute = Char126dashLoginRouteRouteImport.update({
  id: '/~dash/$login',
  path: '/~dash/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126dashLoginIndexRoute = Char126dashLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char126dashLoginRouteRoute,
} as any)
const Char126dashLoginRequestsRoute =
  Char126dashLoginRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => Char126dashLoginRouteRoute,
  } as any)
const CreditsAddIdRoute = CreditsAddIdRouteImport.update({
  id: '/credits/add/$id',
  path: '/credits/add/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126dashLoginSettingsTokensRoute =
  Char126dashLoginSettingsTokensRouteImport.update({
    id: '/settings/tokens',
    path: '/settings/tokens',
    getParentRoute: () => Char126dashLoginRouteRoute,
  } as any)
const Char126dashLoginSettingsMembersRoute =
  Char126dashLoginSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => Char126dashLoginRouteRoute,
  } as any)
const Char126dashLoginSettingsGeneralRoute =
  Char126dashLoginSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => Char126dashLoginRouteRoute,
  } as any)
const Char126dashLoginSettingsBillingRoute =
  Char126dashLoginSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => Char126dashLoginRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/~dash/$login': typeof Char126dashLoginRouteRouteWithChildren
  '/auth/device': typeof AuthDeviceRoute
  '/auth/error': typeof AuthErrorRoute
  '/invite/$token': typeof InviteTokenRoute
  '/credits/add/$id': typeof CreditsAddIdRoute
  '/~dash/$login/requests': typeof Char126dashLoginRequestsRoute
  '/~dash/$login/': typeof Char126dashLoginIndexRoute
  '/~dash/$login/settings/billing': typeof Char126dashLoginSettingsBillingRoute
  '/~dash/$login/settings/general': typeof Char126dashLoginSettingsGeneralRoute
  '/~dash/$login/settings/members': typeof Char126dashLoginSettingsMembersRoute
  '/~dash/$login/settings/tokens': typeof Char126dashLoginSettingsTokensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/auth/device': typeof AuthDeviceRoute
  '/auth/error': typeof AuthErrorRoute
  '/invite/$token': typeof InviteTokenRoute
  '/credits/add/$id': typeof CreditsAddIdRoute
  '/~dash/$login/requests': typeof Char126dashLoginRequestsRoute
  '/~dash/$login': typeof Char126dashLoginIndexRoute
  '/~dash/$login/settings/billing': typeof Char126dashLoginSettingsBillingRoute
  '/~dash/$login/settings/general': typeof Char126dashLoginSettingsGeneralRoute
  '/~dash/$login/settings/members': typeof Char126dashLoginSettingsMembersRoute
  '/~dash/$login/settings/tokens': typeof Char126dashLoginSettingsTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/~dash/$login': typeof Char126dashLoginRouteRouteWithChildren
  '/auth/device': typeof AuthDeviceRoute
  '/auth/error': typeof AuthErrorRoute
  '/invite/$token': typeof InviteTokenRoute
  '/credits/add/$id': typeof CreditsAddIdRoute
  '/~dash/$login/requests': typeof Char126dashLoginRequestsRoute
  '/~dash/$login/': typeof Char126dashLoginIndexRoute
  '/~dash/$login/settings/billing': typeof Char126dashLoginSettingsBillingRoute
  '/~dash/$login/settings/general': typeof Char126dashLoginSettingsGeneralRoute
  '/~dash/$login/settings/members': typeof Char126dashLoginSettingsMembersRoute
  '/~dash/$login/settings/tokens': typeof Char126dashLoginSettingsTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/playground'
    | '/~dash/$login'
    | '/auth/device'
    | '/auth/error'
    | '/invite/$token'
    | '/credits/add/$id'
    | '/~dash/$login/requests'
    | '/~dash/$login/'
    | '/~dash/$login/settings/billing'
    | '/~dash/$login/settings/general'
    | '/~dash/$login/settings/members'
    | '/~dash/$login/settings/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/playground'
    | '/auth/device'
    | '/auth/error'
    | '/invite/$token'
    | '/credits/add/$id'
    | '/~dash/$login/requests'
    | '/~dash/$login'
    | '/~dash/$login/settings/billing'
    | '/~dash/$login/settings/general'
    | '/~dash/$login/settings/members'
    | '/~dash/$login/settings/tokens'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/playground'
    | '/~dash/$login'
    | '/auth/device'
    | '/auth/error'
    | '/invite/$token'
    | '/credits/add/$id'
    | '/~dash/$login/requests'
    | '/~dash/$login/'
    | '/~dash/$login/settings/billing'
    | '/~dash/$login/settings/general'
    | '/~dash/$login/settings/members'
    | '/~dash/$login/settings/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
  Char126dashLoginRouteRoute: typeof Char126dashLoginRouteRouteWithChildren
  AuthDeviceRoute: typeof AuthDeviceRoute
  AuthErrorRoute: typeof AuthErrorRoute
  InviteTokenRoute: typeof InviteTokenRoute
  CreditsAddIdRoute: typeof CreditsAddIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~dash/$login': {
      id: '/~dash/$login'
      path: '/~dash/$login'
      fullPath: '/~dash/$login'
      preLoaderRoute: typeof Char126dashLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~dash/$login/': {
      id: '/~dash/$login/'
      path: '/'
      fullPath: '/~dash/$login/'
      preLoaderRoute: typeof Char126dashLoginIndexRouteImport
      parentRoute: typeof Char126dashLoginRouteRoute
    }
    '/~dash/$login/requests': {
      id: '/~dash/$login/requests'
      path: '/requests'
      fullPath: '/~dash/$login/requests'
      preLoaderRoute: typeof Char126dashLoginRequestsRouteImport
      parentRoute: typeof Char126dashLoginRouteRoute
    }
    '/credits/add/$id': {
      id: '/credits/add/$id'
      path: '/credits/add/$id'
      fullPath: '/credits/add/$id'
      preLoaderRoute: typeof CreditsAddIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~dash/$login/settings/tokens': {
      id: '/~dash/$login/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/~dash/$login/settings/tokens'
      preLoaderRoute: typeof Char126dashLoginSettingsTokensRouteImport
      parentRoute: typeof Char126dashLoginRouteRoute
    }
    '/~dash/$login/settings/members': {
      id: '/~dash/$login/settings/members'
      path: '/settings/members'
      fullPath: '/~dash/$login/settings/members'
      preLoaderRoute: typeof Char126dashLoginSettingsMembersRouteImport
      parentRoute: typeof Char126dashLoginRouteRoute
    }
    '/~dash/$login/settings/general': {
      id: '/~dash/$login/settings/general'
      path: '/settings/general'
      fullPath: '/~dash/$login/settings/general'
      preLoaderRoute: typeof Char126dashLoginSettingsGeneralRouteImport
      parentRoute: typeof Char126dashLoginRouteRoute
    }
    '/~dash/$login/settings/billing': {
      id: '/~dash/$login/settings/billing'
      path: '/settings/billing'
      fullPath: '/~dash/$login/settings/billing'
      preLoaderRoute: typeof Char126dashLoginSettingsBillingRouteImport
      parentRoute: typeof Char126dashLoginRouteRoute
    }
  }
}

interface Char126dashLoginRouteRouteChildren {
  Char126dashLoginRequestsRoute: typeof Char126dashLoginRequestsRoute
  Char126dashLoginIndexRoute: typeof Char126dashLoginIndexRoute
  Char126dashLoginSettingsBillingRoute: typeof Char126dashLoginSettingsBillingRoute
  Char126dashLoginSettingsGeneralRoute: typeof Char126dashLoginSettingsGeneralRoute
  Char126dashLoginSettingsMembersRoute: typeof Char126dashLoginSettingsMembersRoute
  Char126dashLoginSettingsTokensRoute: typeof Char126dashLoginSettingsTokensRoute
}

const Char126dashLoginRouteRouteChildren: Char126dashLoginRouteRouteChildren = {
  Char126dashLoginRequestsRoute: Char126dashLoginRequestsRoute,
  Char126dashLoginIndexRoute: Char126dashLoginIndexRoute,
  Char126dashLoginSettingsBillingRoute: Char126dashLoginSettingsBillingRoute,
  Char126dashLoginSettingsGeneralRoute: Char126dashLoginSettingsGeneralRoute,
  Char126dashLoginSettingsMembersRoute: Char126dashLoginSettingsMembersRoute,
  Char126dashLoginSettingsTokensRoute: Char126dashLoginSettingsTokensRoute,
}

const Char126dashLoginRouteRouteWithChildren =
  Char126dashLoginRouteRoute._addFileChildren(
    Char126dashLoginRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
  Char126dashLoginRouteRoute: Char126dashLoginRouteRouteWithChildren,
  AuthDeviceRoute: AuthDeviceRoute,
  AuthErrorRoute: AuthErrorRoute,
  InviteTokenRoute: InviteTokenRoute,
  CreditsAddIdRoute: CreditsAddIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
