/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckRouteImport } from './routes/check'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as Char126orgSlugRouteRouteImport } from './routes/~org.$slug/route'
import { Route as Char126orgSlugIndexRouteImport } from './routes/~org.$slug/index'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126orgSlugRouteRoute = Char126orgSlugRouteRouteImport.update({
  id: '/~org/$slug',
  path: '/~org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126orgSlugIndexRoute = Char126orgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char126orgSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/playground': typeof PlaygroundRoute
  '/~org/$slug': typeof Char126orgSlugRouteRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/~org/$slug/': typeof Char126orgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/playground': typeof PlaygroundRoute
  '/auth/error': typeof AuthErrorRoute
  '/~org/$slug': typeof Char126orgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/playground': typeof PlaygroundRoute
  '/~org/$slug': typeof Char126orgSlugRouteRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/~org/$slug/': typeof Char126orgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check'
    | '/login'
    | '/new'
    | '/playground'
    | '/~org/$slug'
    | '/auth/error'
    | '/~org/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check'
    | '/login'
    | '/new'
    | '/playground'
    | '/auth/error'
    | '/~org/$slug'
  id:
    | '__root__'
    | '/'
    | '/check'
    | '/login'
    | '/new'
    | '/playground'
    | '/~org/$slug'
    | '/auth/error'
    | '/~org/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckRoute: typeof CheckRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  PlaygroundRoute: typeof PlaygroundRoute
  Char126orgSlugRouteRoute: typeof Char126orgSlugRouteRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~org/$slug': {
      id: '/~org/$slug'
      path: '/~org/$slug'
      fullPath: '/~org/$slug'
      preLoaderRoute: typeof Char126orgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~org/$slug/': {
      id: '/~org/$slug/'
      path: '/'
      fullPath: '/~org/$slug/'
      preLoaderRoute: typeof Char126orgSlugIndexRouteImport
      parentRoute: typeof Char126orgSlugRouteRoute
    }
  }
}

interface Char126orgSlugRouteRouteChildren {
  Char126orgSlugIndexRoute: typeof Char126orgSlugIndexRoute
}

const Char126orgSlugRouteRouteChildren: Char126orgSlugRouteRouteChildren = {
  Char126orgSlugIndexRoute: Char126orgSlugIndexRoute,
}

const Char126orgSlugRouteRouteWithChildren =
  Char126orgSlugRouteRoute._addFileChildren(Char126orgSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckRoute: CheckRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  PlaygroundRoute: PlaygroundRoute,
  Char126orgSlugRouteRoute: Char126orgSlugRouteRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
