name: Check install.sh

on:
  pull_request:
    paths:
      - public/install.sh
      - .github/workflows/check_install.yml
  release:
    types: [published]

permissions:
  contents: read

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Shellcheck
        run: shellcheck public/install.sh

  install:
    name: Test (${{ matrix.os }})
    if: github.event_name == 'release'
    needs: shellcheck
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run install script
        run: sh public/install.sh ${{ github.event.release.tag_name }}

      - name: Verify binary
        run: ~/.local/bin/curl.md --version

      - name: Verify aliases
        run: |
          ~/.local/bin/curlmd --version
          ~/.local/bin/md --version
