name: Verify

on:
  workflow_call:
    inputs:
      submodules:
        type: boolean
        default: false
      pro_tests:
        type: boolean
        default: true
  workflow_dispatch:

env:
  WRANGLER_SEND_METRICS: false

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        if: inputs.submodules
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.CORE_APP_ID }}
          private-key: ${{ secrets.CORE_APP_PRIVATE_KEY }}
          repositories: curl.md.pro

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Checkout submodules
        if: inputs.submodules
        run: |
          git config --global url."https://x-access-token:${TOKEN}@github.com/wevm/curl.md.pro".insteadOf "https://github.com/wevm/curl.md.pro"
          git submodule update --init
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Setup
        uses: ./.github/actions/setup-pnpm

      - name: Lint
        run: pnpm check

      - name: Run migrations
        run: pnpm exec wrangler d1 migrations apply DB --local

      - name: Generate types
        run: |
          pnpm gen:types
          pnpm db:codegen

      - name: Check types
        run: pnpm check:types

      - name: Test
        run: pnpm vitest ${{ !inputs.pro_tests && '--project app --project cli' || '' }}

      - name: Build
        run: pnpm build
